#--------------------------------------
# 菜单配置说明
# identifier ： 唯一标识不可重复
# name       ： 菜单显示名称
# pageref    ： 本站点链接地址，与 URL 选其一
# url        ： 站点外部链接地址，以 http 或者 https 开头
# pre        ： 菜单小图标
# weight     ： 显示顺序，字数越小越靠前
# 
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------
main:
  - identifier: home
    name: 首页
    pageref: /
    pre: home
    weight: 1
  - identifier: leetcode
    name: Leetcode
    pageref: /Leetcode
    pre: code
    weight: 2
  - identifier: golang
    name: Golang
    pageref: /Golang
    pre: code
    weight: 3
  - identifier: devops
    name: Devops
    pageref: /devops
    pre: code
    weight: 4
  - identifier: archives
    name: 读书笔记
    pageref: /books
    pre: book
    weight: 5
